{
  "errors": {
    "didnt_block": "사용자나 서버를 차단한 적이 없습니다.",
    "didnt_block_user": "아직 아무도 차단하지 않았습니다.",
    "didnt_block_guild": "아직 어떤 서버도 차단하지 않았습니다.",
    "add": {
      "guild": "서버를 차단 목록에 추가하는 동안 문제가 발생했습니다. 저희에게 문의해주세요.",
      "user": {
        "none": "지정된 사용자가 없습니다.",
        "self": "당연히, 자기 자신을 차단할 수 없습니다.",
        "bot": "봇은 차단할 수 없습니다.",
        "cantadd": "차단 목록에 사용자를 추가하는 도중 오류가 발생했습니다. 저희에게 연락해주세요."
      }
    },
    "remove": {
      "guild": "차단 목록에서 서버를 제거하는 도중 오류가 발생했습니다. 저희에게 연락해주세요.",
      "user": {
        "none": "지정된 사용자가 없습니다.",
        "self": "당연히, 자기 자신을 차단하거나 차단 해제할 수 없습니다.",
        "bot": "봇을 차단하거나 차단 해제할 수 없습니다.",
        "cantremove": "차단 목록에서 사용자를 제거하는 동안 오류가 발생했습니다. 저희에게 문의해주세요."
      }
    },
    "cant_fetch": {
      "user": "사용자를 불러올 수 없습니다.",
      "guild": "서버를 불러올 수 없습니다."
    }
  },
  "your_blocklist": "내 차단 목록",
  "blocked": {
    "users": "차단한 사용자",
    "guilds": "차단한 서버"
  },
  "add": {
    "guild": "{{guildName}} 서버를 차단 목록에 추가했습니다.",
    "user": "{{userName}} 님을 차단 목록에 추가했습니다."
  },
  "remove": {
    "guild": "{{guildName}} 서버를 차단 목록에서 제거했습니다.",
    "user": "{{userName}} 님을 차단 목록에서 제거했습니다."
  }
}
